### ISSUE TITLE
SSH paths - is not a directory

### ISSUE THREAD

**Issue by lerni** [axllent/ssbak#1]
With version 0.1.1 on darwin I see an error-message when trying to backup per SSH like bellow:
```
/usr/local/bin/ssbak save project@domain.tld:/home/project/public_html/0project/current ./test-01.ssbak
Error: project@domain.tld:/home/project/public_html/0project/current is not a directory
```
Same command with `sspak` "works" but hit size limitation. Above SSH paths contain symlinks but it behaves the the same with real paths. Is there something obvious I’m missing?

**Comment by axllent** [comment]
It currently does not support SSH storage, see the very last line in the README under "Limitations".

**Comment by lerni** [comment]
Ohh sorry - I've overlooked that. Thank you for this new implementation of an ol workinghorse! The idea of `--ignore-resampled` is something I had in mind for much to long time now. Inspired form the superb `bigfork/silverstripe-recipe` I started to use ssbak in tandem with php-deployer - deployer does the ssh part now. I can provide a snipped later on if anybody is interested, but testing with xyGB of assets takes time.

**Comment by axllent** [comment]
We've switched to using ssbak at work, in development, staging and production environments, and it's been working great for the last year or so (when we need it). The size limitation of sspak was a real issue/bug that caught us out a couple of times so it just made sense for me to rebuild it in something far more efficient than PHP.  I haven't had the need for SSH, so I haven't built it in, but it is something I potentially plan to add at some stage.

I'm glad you are able to use it though!
