### ISSUE TITLE
SS_DATABASE_CHOOSE_NAME=true

### ISSUE THREAD

**Issue by lerni** [axllent/ssbak#2]
Locally I work with `SS_DATABASE_CHOOSE_NAME=true` - this sets a DatababseName based on directory the project is in. Looks like ssbak fails to read this - it works if I set `SS_DATABASE_NAME` explicit. https://docs.silverstripe.org/en/4/getting_started/environment_management/#core-environment-variables

**Comment by axllent** [comment]
Thanks @lerni - I have added support for this in the latest release 0.1.2.

Could you please test this and report back?

**Comment by lerni** [comment]
Thank you so much for adding this feature so quickly! Looks like everything seems to work :thumbsup: :100:

**Comment by axllent** [comment]
Awesome, thanks for the feedback!
