### ISSUE TITLE
Wrong naming of "assets" on ssbak save --assets file.sspak

### ISSUE THREAD

**Issue by lerni** [axllent/ssbak#3]
I see a strange issue with naming of assets-folder after unpacking - strange cos sometimes the directory (in the tarball already) is named `ts` or `ets` - however the first few letters are missing. Looks like this happens on packing - not on unpacking.l see the same if I manually unpack the file. Actually I packed with linux_amd64 0.1.3 and try to unpack on osX with darwin_amd64.

**Comment by axllent** [comment]
@lerni This is very strange indeed. Are you possibly able to send me a sspak (file generated with ssbak) which has this issue? I've packaked and extracted probably more than 100 projects and never seen (or noticed) this issue.

**Comment by axllent** [comment]
Just for reference, an sspak file is actually just a standard tar file which contains (normally) two archives inside (one for db, the other assets). I just want to see what your ssbak is generating, and work backwards from there.

**Comment by axllent** [comment]
Thanks @lerni for the email, file and screencast. I'm still completely confused as to what is causing this, and I cannot see anything wrong with your commandline usage of the ssbak.

The sspak file you uploaded looks fine here, and `assets` is called `assets`. Just for reference a *.sspak file is a `.tar` file, not a `.tar.gz` - however your Mac clearly detects this and extracts it correctly (ignoring the incorrect path for now..) as a tar.

Can you confirm something for me please - just so I'm clear. In [your script](https://github.com/lerni/ootstra/blob/master/deploy/recipe/silverstripe.php#L165-L181), you are creating and extracting the backup, as demonstrated in your screencast. Is this being run directly on your Mac, or is it from within a Linux docker container? If it's running on Mac then you appear to be using the Linux binary (although I can't tell what `runLocally()` actually is/does). I'm just trying to make sure that you are using the correct binaries on the right systems, and determine whether the error is within the mac binary or the linux one...

**Comment by axllent** [comment]
@lerni I have hunted (to find the issue) but found nothing. 

So using the same sspak file you provided me, I decided to try it on my Mac (running via a virtual machine ~ Big Sur 11.01 and 11.6) to test - and guess what - the file you sent me extracts perfectly every time. I extracted it via ssbak, as well as the file manager (like you did by renaming it and clicking on it in the file manager), and terminal utilities (tar) and it extracts every time to `assets`.

So I'm beginning to think it's not the sspak file, nor ssbak - but rather something else on your system (eg: an antivirus program interfering, memory issues, strange mounted filesystem?). 

Just a few ideas to test with: Have you tried manually running those ssbak commands on your Mac outside of your deployment scripts? Do you by any chance have another Mac you can try on? Are you using the Mac version of ssbak on your Mac, and if so, is it the most recent one (I assume it is)?

Lastly, can you check the following commands via the terminal with the sspak file you created (which is causing issues):

```shell
tar -x manawapod-assets-2021-09-25-12-35-34.sspak
tar -ztvf assets.tar.gz
```
On that last command, you should see all your assets listed, and all starting with `assets/`.

If they do start with `assets/` - then try extract them via the commandline:
```shell
tar -xvf assets.tar.gz
```
Does that give you an `assets` folder, or is it renamed again `ets` or similar?

**Comment by lerni** [comment]
Thank you so much for taking the time testing this. Replacing the binary and running the command without deployer/symphony/shell was one of the first things I did - yes I'm on the latest and AFAIK it's `darwin_amd64`. With the commands you wrote, it ended up as `assets` folder. I need some time to come back to this and test it all over with docker / vagrant.

**Comment by axllent** [comment]
Hi @lerni, I'm just checking is there was any more feedback on this?

**Comment by lerni** [comment]
Hey Ralph - sorry for the lake of feedback. Until now I had not made any progress respectively could not find anything and the issue slipped down on my todos, even tough it's still the same :( Since what I see is most probable a rare edge case, I'll close it for now but hopefully 'll find time again, to look into it at some point. Thank you again!
