### ISSUE TITLE
can I run ssbak without installing go

### ISSUE THREAD

**Issue by sunnysideup** [axllent/ssbak#5]
I was wondering if I can run ssbak on ubuntu without installing go. I have tried it and it does not seem to work, but it would be great if I could so I wanted to double-check.

This is what I did:
- downloaded the three linux flavours
- extracted the ssbak file
- made it executable
- tried to run it 

I love what it solves for SSPAK, but it would be great if it could run without installing stuff - which is not always straightforward on a server - so I really hope this can run without installing go.

**Comment by axllent** [comment]
Hey Nic. Yes definitely no need to install Go as there's a static pre-compiled binary for all major systems! You'd probably be wanting the Linux amd64 version. 

```
wget https://github.com/axllent/ssbak/releases/download/1.1.0/ssbak_linux_amd64.tar.gz
tar zxvf ssbak_linux_amd64.tar.gz
./ssbak -h
```
Does that not work for you?

**Comment by axllent** [comment]
@sunnysideup ?

**Comment by sunnysideup** [comment]
yes that worked!

**Comment by sunnysideup** [comment]
I guess what may have happened is that I simply ran: 
`ssbak` 
after I ran 
`chmod +x ssbak`
It might be nice if it would just run
`ssbak -h` if you ran `ssbak`

just like, for example, `npm`

**Comment by sunnysideup** [comment]
THANK YOU FOR YOUR HELP!

**Comment by axllent** [comment]
Actually `ssbak` is the same as `ssbak -h` (it already does that) :) There also shouldn't be any requirement to change/set execution permissions after extracting the binary from the tag.gz, however if you have copied the file from elsewhere (eg: over ssh) then I guess it may have lost that.
